### PR TITLE
Add whitelist of regions with no region enter events

### LINKED ISSUE #87: Handling of "expected" region exists w/o enter (e.g. threading)
I added tests for using the module with Pythons builtin `threading` lib which simply creates 2 `Thread`s and runs a test function in each of them. The tests fail due to region exit events without a region enter which is expected.

What happens is:
- `threading.settrace(func)` is called (by scorep) to notify the threading module about the trace function
- the `Thread.start` method spawns a new thread which executes a `_bootstrap` method (which calls a `_bootstrap_inner` method)
- `sys.settrace(func)` is called (by threading) to install the trace function in the new thread
- now the user-defined function is run the new thread
- the 2 `_bootstrap` methods return leading to the exit-without-enter issue

Given that there is no way to avoid this I'd propose to simply ignore the error in the `region_end` function for known region names. And add `threading:_bootstrap_inner` and `threading:_bootstrap` to those.

Additionally I'd also ignore errors for regions starting with `_pydev_bundle.pydev_monkey` which occur e.g. when debugging in VisualStudioCode.

### PR DESCRIPTION
**Pull request by Flamefire**
Avoids confusing warning when it is known that no region enter event can
be recorded. This is true for the threading::bootstrap methods as they
are called right after creating a new thread but before the instrumenter is enabled

Fixes #87

### CODE REVIEW

**Comment by AndreasGocht** [comment]
And the python2 tests broke again 😄 . I assume there is a different function name you need to whitelist here?

**Comment by Flamefire** [comment]
Yes they use double underscore -.-
Fixed but made version dependent for more lookup speed. When the list grows longer it could be sorted and binary search can be used. But for now this should be enough

**Comment by AndreasGocht** [comment]
please stop using force push ... it took me three mails from github to find actually that one, that does not point to nowhere.

**Comment by AndreasGocht** [comment]
>  Fixed but made version dependent for more lookup speed. When the list grows longer it could be sorted and binary search can be used. But for now this should be enough

You are over optimising. Four entries, which are parsed only if an error occurs, are not worth optimising. There is currently no need for the version check here. Instead, we do have a danger of ending up with thousands of ifdefs for different python version. Moreover, if we end up with a list of thousands of elements at this place so that differentiation would have a real performance impact, we would have made something wrong.

**Comment by AndreasGocht** [comment]
> I think you are exaggerating a lot here. I find this even clearer as it shows why the single- and double-underscore names are there which avoids a potentially wrong comment and additionally improves speed (which is as you mentioned minor in this case). So that "optimization" is very simple and even improves readability.

which would a comment do as well. Anyway ... if I ever stumble about this because of reasons, its gone.

> That was only to fixup the most recently pushed commit which contained an error. No comments were there so no history lost. As for mails you can (and likely eventually will) use the most recent one or go to the PR directly. I'd consider that "going nowhere" a feature as it avoids commenting on a known wrong commit for which a fixup already exists.

Nope. It was the last mail, which went to nowhere, and actually its the easiest way to go from Mail to the related GitHub repo.

**Pull request merged**
